apiVersion: v1
kind: Service
metadata:
  name: vwt-svc
spec:
  selector:
    app: vwt
  ports:
    - name: vwt
      port: 4500
      targetPort: 4500
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vwt
spec:
  selector:
    matchLabels:
      app: vwt
  replicas: 2
  template:
    metadata:
      labels:
        app: vwt
    spec:
      containers:
        - name: vwt
          image: docker.io/kebeney/beren:vwt-0.0.53
          env:
            - name: VLT_PROTO
              value: https
            - name: VLT_IP
              value: kberen.com
            - name: VLT_TCP_PORT
              value: '8200'
            - name: LOG_PROTO
              value: https 
            - name: LOG_IP
              value: log-svc.yaml
            - name: LOG_HTTP_PORT
              value: '4600'
            - name: AUT_PROTO
              value: https
            - name: AUT_IP
              value: aut-svc.default
            - name: AUT_HTTP_PORT
              value: '4000'
            - name: JEN_PROTO
              value: https
            - name: JEN_IP
              value: jen-svc-default
            - name: JEN_HTTP_PORT
              value: '4400'
            - name: MPS_PROTO
              value: https
            - name: MPS_IP
              value: mps-svc.default
            - name: MPS_HTTP_PORT
              value: '4300'
            - name: TARGET_DB
              value: vwt
          ports:
            - name: vwt
              containerPort: 4500
          volumeMounts:
            - name: aut-volume
              mountPath: /opt/vwt/data
            - name: tls-certs
              mountPath: /opt/vwt/tls
              readOnly: false
      volumes:
        - name: vwt-volume
          persistentVolumeClaim:
            claimName: vwt-pvc
        - name: tls-certs
          secret:
            secretName: beren-tls
            defaultMode: 0600
