apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vwt-pvc
spec:
  storageClassName: local-storage
  volumeName: vwt-pv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi