apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mps-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mps.cberen.com
      secretName: cberen-tls
  rules:
  - host: mps.cberen.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: mps-svc
              port: 
                number: 4300