apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: rnt-ingress
spec:
  # ingressClassName: nginx
  tls:
  - hosts:
    - rnt.kberen.com
    secretName: le-tls
  rules:
  - host: rnt.kberen.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: rnt-svc
            port: 
              number: 4200