apiVersion: v1
kind: Secret
metadata:
  name: cberen-tls
type: generic
data:
  certificate.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQXMrZ0F3SUJBZ0lVZGlPcWhHTmVi
    YkhSYUFhRktwZUl1Z25VQ1FVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tR
    a1ZTUlU0c0lFeE1RekFlRncweU16QTJNakl4TVRRM01UUmFGdzB5TkRBMgpNakV4TVRRM01UUmFN
    QlV4RXpBUkJnTlZCQU1NQ2tKRlVrVk9MQ0JNVEVNd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFB
    NElCRHdBd2dnRUtBb0lCQVFEWVNUOEV3dGRzTlB5U3FMQko4cnVsSWt6RnF4YUtmaFkra3QvQjY1
    ZVUKS25GbUs3OWtUbVRQMGlQTVBCZmlKa243YzhTTGRwdldYalkxbjVlVHFETVo5amRTN3ZicThn
    dVlpcTM4UkdMagpJVjgyWDd6MHA3ZW4yZkdKWnI5blhHT3dtUllLcmZpYTJzR0pWbnBrb3hWdmdx
    RDQ4dThMbVFSVTE5VkVPcmFlCnAvSFd2cENDQzVUMDNKZmgwRHl2eU5CRmp1NmtHU3BsNjkrdGJS
    M0w4cDNTMDdMQlkyK2VGL2s4b1JPeGIralcKZEtWUGc5YVhnK1hkUExQTEpXeVUvZVRPVnJaUisx
    YlhnTEFwa2tndFFRcjRXWGRsd3dWQ1hrSFE3WVcwMFVYVwpNZWZTcnlsb1A2dXByWXZLSjhSdUEw
    eWZzc3hHOWFlc2E4T21wd0pYTVo4dEFnTUJBQUdqZ2dFdE1JSUJLVEFMCkJnTlZIUThFQkFNQ0JE
    QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3Z2VVR0ExVWRFUVNCM1RDQjJvY0UKd0toV0JJ
    Y0V3S2hXeVljRXdLaFd5NGNFd0toV3pJY0V3S2hXelljRXdLaFd6b2NFd0toV3o0Y0V3S2hXMElj
    RQp3S2hXMFljRXdLaFcwb2NFd0toVzA0Y0V3S2hXMUlJS1kySmxjbVZ1TG1OdmJZSU9ZWFYwTG1O
    aVpYSmxiaTVqCmIyMkNFRzloZFhSb0xtTmlaWEpsYmk1amIyMkNEbTF3Y3k1alltVnlaVzR1WTI5
    dGdnNXFaVzR1WTJKbGNtVnUKTG1OdmJZSU9iRzluTG1OaVpYSmxiaTVqYjIyQ0VtRmpZV1JsYlhr
    dVkySmxjbVZ1TG1OdmJZSU9jbTUwTG1OaQpaWEpsYmk1amIyMkNEblozZEM1alltVnlaVzR1WTI5
    dE1CMEdBMVVkRGdRV0JCUnlibFQ4SUVmRGZ3QlJSMm5xCjNWRVZjTnJzeHpBTkJna3Foa2lHOXcw
    QkFRc0ZBQU9DQVFFQXdrM08rZkhQT3ZaUG1qZXNRcERWaGRDdGxneFQKWVdQNWRvSVdZdGo3NE1i
    L3VTdzV2NVJTOTRVdmRLMzhwMDlNd3dMaStZWUEzNXpIYlRIVVRJQ1h4bFZxRStUWQpVNW5Jak4x
    STE1dDB1OGE0NGJRcDRvZkh3d0FCUDVLZUh3aU9MR2pPL0ZRUXBDRkdhcnBqUGdhKzh3dUUvTVZG
    CnRBQnlpV1NMRGpkM3QyTURIbkZreFpHTyt1dFVaTk4zMVFnZVFlRGtRcy8vc1J3dnhjMGJmeW92
    T1NPTDRaa2gKM0tZbEdLTE9KUGNEZVdMcnFBdkFXcmxsTmpOc1p3VXFFcSt4ZmJOd1ZVU1JaL29y
    WDZMUUVXUkI0a3JGdUpoawpwaXFMbmxTS2hEQ2RCdWN2d3N6WFpGcWtjTUxlYkdPbndFSXBLbmgw
    RnJRZU1qOENnNHo2NEw2OHNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  priv-key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRFlTVDhFd3Rkc05QeVMKcUxCSjhydWxJa3pGcXhhS2ZoWStr
    dC9CNjVlVUtuRm1LNzlrVG1UUDBpUE1QQmZpSmtuN2M4U0xkcHZXWGpZMQpuNWVUcURNWjlqZFM3
    dmJxOGd1WWlxMzhSR0xqSVY4Mlg3ejBwN2VuMmZHSlpyOW5YR093bVJZS3JmaWEyc0dKClZucGtv
    eFZ2Z3FENDh1OExtUVJVMTlWRU9yYWVwL0hXdnBDQ0M1VDAzSmZoMER5dnlOQkZqdTZrR1NwbDY5
    K3QKYlIzTDhwM1MwN0xCWTIrZUYvazhvUk94YitqV2RLVlBnOWFYZytYZFBMUExKV3lVL2VUT1Zy
    WlIrMWJYZ0xBcApra2d0UVFyNFdYZGx3d1ZDWGtIUTdZVzAwVVhXTWVmU3J5bG9QNnVwcll2S0o4
    UnVBMHlmc3N4RzlhZXNhOE9tCnB3SlhNWjh0QWdNQkFBRUNnZ0VBVy9yeWFQVHZwbDMyVit5VFpD
    OXRhN0hsa2w3TExFU284eDJGT1RRVzkzVUIKV3VFWitPOTU0Z1BOSTRzZTRSZEZlVUZuZ2FRRWJD
    c094TWxGTGc5bkJCQjR3TFZObnVjbTFVMk01bTZ5MjBNUworYzNIVHdpUWl6cWRoTUNFZjlHRHQ5
    T3kwd0hmYXdQRE1NUHRNeVZEOVhOSlAvWVlnUWNuRjJuZWtiQ2lmMS9HCnBMYzZIMndZZDEyRXk1
    aitHQmd0ejIvazUxTmp6NWFPTDJaRHUra0EzSnVkK0pCYlVCUWZxWkw3TGpyLzN2cmEKdU9EeFEw
    d3RhN3Awak5lcDc1YmVGVnpBSWpKUHpZdmQySHhWZTNtWXQvTWdQd282Z2dMSWFDVmRQcDk3Q3p4
    NgppdFFYai9oWkZzSDRCTGUzem1tY1hCc2V3RGg2bGg5RTh5aXlDMzl6NVFLQmdRRGlCRkNiR2lU
    eXUxMlE3a2taCmxpQktOdHJDL3pld25ZMWdVZ1ZuS3k4dmI5SEtlbjFuckNiTVZScWd2SEpUNG1z
    NzJaSTFHTHFSWkJKZFl1Tk8KekRMclpsd05KQzRpRmkzdFY1citVTmFBQkxhd2hGWUpzSEZ1QTVV
    R1N1TnlDTW55THNhV0dHQXlvRlJrWG9DUQpCdkJsaFJsUlJpMTVxQkNOS28yVnVQbjFvd0tCZ1FE
    MCtuZ0pSdEJjVkpNQTRQbk1hT1Z6SmhCOHo3b1dvMXZUCm9hWXk2NCtKZkpDOW5ETEJoTExrbzJJ
    M1BnTFRYZUZMT2I5UUt1S1FjYlZKelc1Vjk3MTNRbUxBZTNDVk1RNEcKVmxCQnBGdThDRUlMeHV3
    UVVTOXhqdU43ODNyQ01CUGZEUlVFMXhhMlB0eE5UWlZUVmt4QnoyTU02bVZFTVpYZQpZc1VWaW5K
    RTd3S0JnQW56OHJEQjEvcXdjWkJlVGUzSWhLZC8vdVl6WXZwdUZibTJJdkxHSGcvU3RzUlozSWZp
    Ck50c3NyRDJEenUwT3ZYWW5RSjhCOWNWTlNObS83dzZiUTJyR1dTdGkrbjBaeU8vNHVhU1ZYcnpJ
    ZUZzUm1OQlkKYXNaVGRnNk80YkUxM2Q3Q1hKQmpobWowVW9NUS9reFpZZUMybWNUUWVGUXhLSGx1
    OUVreG1pQk5Bb0dCQU1rTwpnOVBCUGFKNWV3aSttK1ZxdGQzeWdKZWUrUEE1ZEZUVmw0eTFEZUhk
    elFFQklCcjVLTVZEWG9sT0tJMkd3Qys0CkhrN1NVNDRPOUtXMHAzaUEwZ3Y5L1FSU2l3eTI3UGJB
    Z2kvTmo4aGIwckROdXRLTmZ1MnBRd1JveVBoMDh1b2UKVjREWWNuaHlVT1pVNVZnM1BIREtuMVZy
    VGw5UWZ0cThuMW5WZllFYkFvR0FkK2IvVWdzcGtaL2FqU1RIU0JBMQo2MnZDNm1UbUlseEtNWTlr
    ZDZ5eWFHTjRvbGY2bnZrRmloVHowQ2lMeUVNTHBjeXVGSjYrTjZoRmsrL3l3MzQ1Cjk1UmFzYWd5
    TXhjWXZLUU4vRTN1MzAzRGhKbE9oSHNuYWowWG56Unl2bndobkVhU1FvVWVtVEUyZ1RsRVpMcGoK
    aVkxWm5GWVNNd0grcVJsQTJmWi94clU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
