apiVersion: v1
kind: Secret
metadata:
  name: keb-tls
type: generic
data:
  cert.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGVENDQXYyZ0F3SUJBZ0lVTXM2bWVoYndr
    aTVGT3AvbmtqaldGZlhhOXZZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZSXhDekFKQmdOVkJBWVRB
    a3RGTVEwd0N3WURWUVFJREFSU1NVWlVNUXd3Q2dZRFZRUUhEQU5GVEVReApEakFNQmdOVkJBb01C
    VUpGVWtWT01Rd3dDZ1lEVlFRTERBTkVSVkF4RWpBUUJnTlZCQU1NQ1dKbGNtVnVMbU52CmJURWtN
    Q0lHQ1NxR1NJYjNEUUVKQVJZVlpHVnVhMjlsWTJneE1qQkFaMjFoYVd3dVkyOXRNQjRYRFRJek1E
    WXgKTmpFM01UTXhNVm9YRFRNek1EWXhNekUzTVRNeE1Wb3dnWUl4Q3pBSkJnTlZCQVlUQWt0Rk1R
    MHdDd1lEVlFRSQpEQVJTU1VaVU1Rd3dDZ1lEVlFRSERBTkZURVF4RGpBTUJnTlZCQW9NQlVKRlVr
    Vk9NUXd3Q2dZRFZRUUxEQU5FClJWQXhFakFRQmdOVkJBTU1DV0psY21WdUxtTnZiVEVrTUNJR0NT
    cUdTSWIzRFFFSkFSWVZaR1Z1YTI5bFkyZ3gKTWpCQVoyMWhhV3d1WTI5dE1JSUJJakFOQmdrcWhr
    aUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeEtVNgptL2xFM3RUZnlGUzFMWVdNT3g2LzBa
    dGUxS2NzNlBpNHlGNEpabUFiWVBNeGVocm1HNTlhdDdZc3ZaMmU0K3dNClR3QnozSzc0RDcvWEdk
    cFFPZDNmUzI1OW92aWd0bDBjMjZydkRKbHJxcjg2QmcvdGxzMEZSVDUwUHZNZXJPUksKMUlST3dI
    Ynl3YTRJODUxdFRTTlRpUzNNaThOTGpESVFzenVyaXFlVDdUUC92UnFvTHpnMlEwUDZoQ1grZG5I
    SAo5cVBNNU56d2VNVEo3enJWNUhMQ0xRbkRpSXFCN0ZiblVocVZkQ0tQSWFNUEhPRDhha1FvZWJB
    MzBsKzV3RXQ4CmY5cEpVWnU2TnVReXcrbURkcEszaW1YOWhaWE1BTDBvVWp4aWZ3V0p4ZEhKeWdk
    VXJVcnRxcXQzT1BRTFQ3bWsKQlErdnBtR01RL2Q3aGdLc1ZRSURBUUFCbzRHQU1INHdYUVlEVlIw
    UkJGWXdWSWNFd0toVzBJY0Vmd0FBQVljRQp3S2hXeVljRXdLaFd5NGNFd0toV3pJY0V3S2hXMFlj
    RXdLaFd5b2NFd0toV3pJY0V3S2hXelljRXdLaFd6b2NFCndLaFd6NGNFd0toVzBZY0V3S2hXMG9j
    RXdLaFcwekFkQmdOVkhRNEVGZ1FVZSs5S2plOWhPbktNaTMzN0J5cngKTUJPSDhMd3dEUVlKS29a
    SWh2Y05BUUVMQlFBRGdnRUJBSWx5NDlWd1VzVGdLdzFLek51VjA3UDEvWTNseEN1NgoyN1VoODRz
    OG1kTzFqL2JEVVVvUjR2T1c4c0V0SkF5Qm5kUWJNS3RTK1B5N2VWUk1mTzYzcTNOZmVsWWh4ZzRU
    ClNEeHg3YU5tRXRjVlVSb0xncnBDd3VhZk9LSGRLQXhzY3VGczE3cUdJdXRzY0tKdFRiWksrYUQ1
    aDkvTitEbWMKbTY1V1IrYVdqMjNKVlFlTU1KVk9FT1NETGhMaUdvajNtRFJmUGMxM29rZHBmRFll
    VHVUeElXdUFTaWRudHUrbwpZSGpucFA2K0VNckdqSGlZK1JObDkxYStWSEpNVkRaK3pTMUhLMk15
    c2FhcHdQdzBqdWQ1SkFKMUt0VFRlOGVJCjZDRU5FNGpGQWFlc2wwdlNPMWJmRnF4cThjQjFpbURu
    TGRzaFdseUc2V1UzWlphdm1FYmt4enM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  priv-key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRREVwVHFiK1VUZTFOL0kKVkxVdGhZdzdIci9SbTE3VXB5em8r
    TGpJWGdsbVlCdGc4ekY2R3VZYm4xcTN0aXk5blo3ajdBeFBBSFBjcnZnUAp2OWNaMmxBNTNkOUxi
    bjJpK0tDMlhSemJxdThNbVd1cXZ6b0dEKzJXelFWRlBuUSs4eDZzNUVyVWhFN0FkdkxCCnJnanpu
    VzFOSTFPSkxjeUx3MHVNTWhDek82dUtwNVB0TS8rOUdxZ3ZPRFpEUS9xRUpmNTJjY2Yybzh6azNQ
    QjQKeE1udk90WGtjc0l0Q2NPSWlvSHNWdWRTR3BWMElvOGhvdzhjNFB4cVJDaDVzRGZTWDduQVMz
    eC8ya2xSbTdvMgo1RExENllOMmtyZUtaZjJGbGN3QXZTaFNQR0ovQlluRjBjbktCMVN0U3UycXEz
    YzQ5QXRQdWFRRkQ2K21ZWXhECjkzdUdBcXhWQWdNQkFBRUNnZ0VBQmYreFhrVTRLZUVPRTVjcjhM
    L1FjNVJBVDBWaFd2VGZuSnJMemtiNkcrNm0KSHlyRUVXREZNTVlIZHkrK1JTbU1DWkZ2bmJCYW1I
    cVk5Q2dLeUkzZG9TcEl6ODBHMWFRbWlQR2x1ZmpJc3BaeQpqNkttUXoyVXBxTkovQjhIM2t5OTNK
    SFpTNHJldVNYWHlYdEU2Q09mRERtZDZJTW1hSVFVWjZvMlVyVnBDZ0Y5CmJoZVhtOFY1dFIxYitQ
    eGh4WTVnMjlFdXVQZUp3VnlobW5ITmlPenJieUIxK0RMNmVIczd1cnJBTHpjMzNaNFgKMUJTQ2Zk
    MnlsVVpuVkFqenVLck9ScmlibXVuZldwUE8wdnVDaGdST0c4OVZBL3BWeUFxMDdtdGtWY2NDY1B6
    dwp0VnRVOVNEdWxTSXE5QzhYdXEyQnJvUjBXbHVXVTVmTVV4Y0tUV2FOZVFLQmdRRDY3Ny9uYXdR
    bDV3UzIzV3VsCnYyUWpkTmxXYU1ZQitGckd5b01ia3Vsc3A4b1BhQXB3YmQ0b1Y0ZlpOOVV0WmhR
    VU5wcXNaL2hVdmxGYk14aHQKbldiczhNR08xbmI0cTUvZnNsOXZYSC9jTkJTUllSSGhtelUrd0pr
    dUZSK3o5NGtlZ3BMQWljaWUwWkMwYmdVNApkVzdLUGg2TXlzWnBOdEZ0d05lbFBIV2hDUUtCZ1FE
    SW5RZk9BWmxZUFIzUWVOakhRRjVQSHVuSDczZzQzYXRkCjRlK2EzanFDS3hrTVVaR1pCZ2dKamxo
    Tk05eDE3K2dTbWM2WVB5VDQyNDFQZ2luVDdGMThLMFNjMUNCNHhBM3IKeEZiOFFQejlFYmJNOStP
    ZUg4WlNSSzFHd2Z0VVNhZHJBQ1RYa3NrN05rSGhHRWNkMmxDY3g3UmxsY2pCWHU3SwpDLzQweTFp
    ZjdRS0JnUUQ0VEdOSFNjMUE4K2JtU3hKSlg2aG1yU2loSit0RjU4bHJDdGZRWVA0NFZZN0t6OWdF
    Cmg3SmJtTUVEWHd2QmNGQk43L244dnFRcXRtY3FKdFQxSWRyR2VUUU5jb2ttWml3NzNQUXg3UVZY
    anZFTEtWSFkKT3d2a25BNzJXbENVYzB0cXRTa2crelZZY1dVT0pBOW1Ya3pTTWNWbzZ2eUkvNFVi
    Wk1YODZtWTZnUUtCZ0JnYQpWYys0ZlhZT2tjQjBaSWM4QXBpNi9CZWJlL1JKSGNlLzE0dmgyMkc4
    VDl3ZENNTTc2RWROcE9wUnF0RTRxOGRnClYyUVBZaC9NTVNRMlhWUXE5K2h0UW1jZFRYRjFETDhn
    N2RxTTdGaHpnbVVKKzMwS0VFZmVISHQ5M3ZaM2l2ZmUKSW84TUFjVnRkV2pZQStOZ1VZTWtzMVhw
    TXgrWWlsUVlNTWlqRGRqWkFvR0JBUFBBZis3OUR1Z203WFBuMGdHVwpCak1VSmkvSzhkNVM4L1R1
    VktBRGE3b3R6TUdYTmdsaHByN2Q0bnhBQ2l5YkdpenlEQ1daaWFEamhKb0FidnJqCk9sV0R2Mkx1
    a3kxQXhmUzZDM0tlR1UrdzltOEsvMHRGQXM2c0lwZ3k4ODFlS1pGdlRiVUlMZVlaOUV2WVBDeDMK
    UmUvbUYvTFlLY0tGY0NvZStZYTFPdHJvCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  ca.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ3lEQ0NBYkFDQVFBd2dZSXhD
    ekFKQmdOVkJBWVRBa3RGTVEwd0N3WURWUVFJREFSU1NVWlVNUXd3Q2dZRApWUVFIREFORlRFUXhE
    akFNQmdOVkJBb01CVUpGVWtWT01Rd3dDZ1lEVlFRTERBTkVSVkF4RWpBUUJnTlZCQU1NCkNXSmxj
    bVZ1TG1OdmJURWtNQ0lHQ1NxR1NJYjNEUUVKQVJZVlpHVnVhMjlsWTJneE1qQkFaMjFoYVd3dVky
    OXQKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4S1U2bS9sRTN0
    VGZ5RlMxTFlXTQpPeDYvMFp0ZTFLY3M2UGk0eUY0SlptQWJZUE14ZWhybUc1OWF0N1lzdloyZTQr
    d01Ud0J6M0s3NEQ3L1hHZHBRCk9kM2ZTMjU5b3ZpZ3RsMGMyNnJ2REpscnFyODZCZy90bHMwRlJU
    NTBQdk1lck9SSzFJUk93SGJ5d2E0STg1MXQKVFNOVGlTM01pOE5MakRJUXN6dXJpcWVUN1RQL3ZS
    cW9MemcyUTBQNmhDWCtkbkhIOXFQTTVOendlTVRKN3pyVgo1SExDTFFuRGlJcUI3RmJuVWhxVmRD
    S1BJYU1QSE9EOGFrUW9lYkEzMGwrNXdFdDhmOXBKVVp1Nk51UXl3K21ECmRwSzNpbVg5aFpYTUFM
    MG9VanhpZndXSnhkSEp5Z2RVclVydHFxdDNPUFFMVDdta0JRK3ZwbUdNUS9kN2hnS3MKVlFJREFR
    QUJvQUF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUUrcmtJa0sxWGZXdVhrUStyWFdEbGdQV2ox
    aApvZG9BVkRHMzljQlNXNS92WjFOcGk4djJMMFV2aGIrMDJPVndsQVUzUlBDRmtJTmJCeG5ZckY3
    bGN3c2ErSzJhCngyUEJqTWRCSmhXRHJ5WmtuQVdSR0xsdDkvTStGZ3g0eFFkeEk2ZURKTFcrSXJE
    MG1kNGg2VFZ1b3lqdjUzbE8KdG5MbjBTKzhmdnJjYkVmWmpLaDVqS3N6ZTlXTzd4TXQvTi96YTk5
    ZGNWQUxoVE5FTzV4SVdyZVJ0djZ0SXkwTgp3b3cwNU93Vng1Yit3ZHZsWTRSL0hRc0JuQVpJcG82
    Y2JUTTF2N2ZvTFBrZmlaZ0d0dTc2L3Fya2NDVkh6MExHCitJQzFOK05jNE9qTWt4TFBNZmw4Q0dx
    UnAyeXpaU2VwVDA4Sk1aNWdwSjQvWlE2Yi9MNWJzWEJEbllJPQotLS0tLUVORCBDRVJUSUZJQ0FU
    RSBSRVFVRVNULS0tLS0K