apiVersion: v1
kind: Secret
metadata:
  name: kebenei-tls
type: generic
data:
  fullchain.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUwRENDQTdpZ0F3SUJBZ0lTQkVVelpvbHAz
    YSs3WW9PemUxY3ZyRjlYTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRN
    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlN
    ekEyTXpBd05qUTFNakZhRncweU16QTVNamd3TmpRMU1qQmFNQll4RkRBU0JnTlZCQU1UCkMydGxZ
    bVZ1WldrdVkyOXRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVnWThjVUZyaVJX
    TDMKdnV3cUc1ZW9XN09mZWd0VDdYOVJHQm5OMGxHSElTZG9SaFMrWllybHZKY2xzM0lmR2FZNE9v
    Q21lY1lJbnRDMgplcEREbER6bklxT0NBc1V3Z2dMQk1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBZEJn
    TlZIU1VFRmpBVUJnZ3JCZ0VGCkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FE
    QWRCZ05WSFE0RUZnUVVtSll5MDgwYWZMY0wKT3NnNGpwZEo4ZFNVbE5Fd0h3WURWUjBqQkJnd0Zv
    QVVGQzZ6RjdkWVZzdXVVQWxBNWgrdm5Zc1V3c1l3VlFZSQpLd1lCQlFVSEFRRUVTVEJITUNFR0ND
    c0dBUVVGQnpBQmhoVm9kSFJ3T2k4dmNqTXVieTVzWlc1amNpNXZjbWN3CklnWUlLd1lCQlFVSE1B
    S0dGbWgwZEhBNkx5OXlNeTVwTG14bGJtTnlMbTl5Wnk4d2djMEdBMVVkRVFTQnhUQ0IKd29JVFlX
    TmhaR1Z0ZVM1clpXSmxibVZwTG1OdmJZSVBZWFYwTG10bFltVnVaV2t1WTI5dGdoTm5jbUZtWVc1
    aApMbXRsWW1WdVpXa3VZMjl0Z2c5cVpXNHVhMlZpWlc1bGFTNWpiMjJDQzJ0bFltVnVaV2t1WTI5
    dGdnOXNiMmN1CmEyVmlaVzVsYVM1amIyMkNEMjF3Y3k1clpXSmxibVZwTG1OdmJZSVJiMkYxZEdn
    dWEyVmlaVzVsYVM1amIyMkMKRUhCeWIyMHVhMlZpWlc1bGFTNWpiMjJDRDNKdWRDNXJaV0psYm1W
    cExtTnZiWUlQZG5kMExtdGxZbVZ1WldrdQpZMjl0TUJNR0ExVWRJQVFNTUFvd0NBWUdaNEVNQVFJ
    Qk1JSUJCQVlLS3dZQkJBSFdlUUlFQWdTQjlRU0I4Z0R3CkFIWUFlaktNVk5pM0xiWWc2ampnVWg3
    cGhCWndNaE9GVFR2U0s4RTZWNk5TNjFJQUFBR0pDME9FM2dBQUJBTUEKUnpCRkFpRUExbzFWaFRZ
    U3VmdElKWi9iQmJFNWlTcFpWNmxCZEZUM0JGL0doeE1xZXVrQ0lHMDFVOXEvTURNUApISHpDSWZD
    dHRiNHRKd2tOQVN1NFJUZmNzSVUyYk1xUUFIWUE2RDdRMmo3MUJqVXk1MWNvdklscnlRUFR5OUVS
    CmErenJhZUYzZlcwR3ZXNEFBQUdKQzBPRkJ3QUFCQU1BUnpCRkFpRUFoYjVsTit5ZDFMM2RKSERM
    d1Bod1k0UjkKVFpYb1c0YmFkNDcvOW1LNndZVUNJRi83QzlVbkRIZ1FyV04xVmx3clAvRENTOC9L
    YU9GZXpRbGxUZVpZOXpLWApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJDd0dveDlJNU5qSlVi
    VzQ4ZWJ2RVBJY0pVbGdqWVhzNzNITWx4CkswaHNwaTVqV3VTRmJRYk1FOHZZRXdKVDcvc3J0ck5x
    bVpoeVhwU0cydzBuUWs3R0NKRlJ6V1hxU3dKZGhVYjcKYnpDMUNNOHJXOVpGbzVWV3pvcVhpTWhh
    TzRJL2EzOEdrMGp2SStJa2FIbEhiYmorOHZ5NGFXWEJCTlpZeUQvOQpTcm9kVUdRT0hmUmdJZmIv
    YTJ6aEhCaUZhcUVQUVE2ZjVCcWxPa21yTnZ0UEQySkRGNUx3M2JzNHNUZkRGM3AvCnlNOHZpbXpr
    QXNOV3JqTWlTSlNCZkFvT3l0MDE0d1ZuY3JYMlNBeGdlSGFGeEQ3ZkRDbEZLdU9nd2MvNkdUZ1MK
    TzE1aXZGZTM0aWxHV3dsYVRGSUJIWGYxTFVxdVV6V0U2b01PN0ltTEZZeHJ1YjNECi0tLS0tRU5E
    IENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZGakNDQXY2
    Z0F3SUJBZ0lSQUpFckNFclBEQmluVS9iV0xpV25YMW93RFFZSktvWklodmNOQVFFTEJRQXcKVHpF
    TE1Ba0dBMVVFQmhNQ1ZWTXhLVEFuQmdOVkJBb1RJRWx1ZEdWeWJtVjBJRk5sWTNWeWFYUjVJRkps
    YzJWaApjbU5vSUVkeWIzVndNUlV3RXdZRFZRUURFd3hKVTFKSElGSnZiM1FnV0RFd0hoY05NakF3
    T1RBME1EQXdNREF3CldoY05NalV3T1RFMU1UWXdNREF3V2pBeU1Rc3dDUVlEVlFRR0V3SlZVekVX
    TUJRR0ExVUVDaE1OVEdWMEozTWcKUlc1amNubHdkREVMTUFrR0ExVUVBeE1DVWpNd2dnRWlNQTBH
    Q1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFDN0FoVW96UGFnbE5NUEV1eU5WWkxE
    K0lMeG1hWjZRb2luWFNhcXRTdTV4VXl4cjQ1citYWElvOWNQClI1UVVWVFZYako2b29qa1o5WUk4
    UXFsT2J2VTd3eTdiamNDd1hQTlpPT2Z0ejJud1dnc2J2c0NVSkNXSCtqZHgKc3hQbkhLemhtKy9i
    NUR0RlVrV1dxY0ZUempUSVV1NjFydTJQM21CdzRxVlVxN1p0RHBlbFFEUnJLOU84WnV0bQpOSHo2
    YTR1UFZ5bVorREFYWGJweWIvdUJ4YTNTaGxnOUY4Zm5DYnZ4Sy9lRzNNSGFjVjNVUnVQTXJTWEJp
    THhnClozVm1zL0VZOTZKYzVsUC9Pb2kyUjZYL0V4anFtQWwzUDUxVCtjOEI1ZldtY0JjVXIyT2sv
    NW16azUzY1U2Y0cKL2tpRkhhRnByaVYxdXhQTVVnUDE3VkdoaTlzVkFnTUJBQUdqZ2dFSU1JSUJC
    REFPQmdOVkhROEJBZjhFQkFNQwpBWVl3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dB
    UVVGQndNQk1CSUdBMVVkRXdFQi93UUlNQVlCCkFmOENBUUF3SFFZRFZSME9CQllFRkJRdXN4ZTNX
    RmJMcmxBSlFPWWZyNTJMRk1MR01COEdBMVVkSXdRWU1CYUEKRkhtMFdlWjd0dVhrQVhPQUNJaklH
    bGoyNlp0dU1ESUdDQ3NHQVFVRkJ3RUJCQ1l3SkRBaUJnZ3JCZ0VGQlFjdwpBb1lXYUhSMGNEb3ZM
    M2d4TG1rdWJHVnVZM0l1YjNKbkx6QW5CZ05WSFI4RUlEQWVNQnlnR3FBWWhoWm9kSFJ3Ck9pOHZl
    REV1WXk1c1pXNWpjaTV2Y21jdk1DSUdBMVVkSUFRYk1Ca3dDQVlHWjRFTUFRSUJNQTBHQ3lzR0FR
    UUIKZ3Q4VEFRRUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUNGeWs1SFBxUDNoVVNGdk5WbmVM
    S1lZNjExVFI2VwpQVE5sY2xRdGdhRHF3KzM0SUw5ZnpMZHdBTGR1Ty9aZWxON2tJSittNzR1eUEr
    ZWl0Ulk4a2M2MDdUa0M1M3dsCmlrZm1aVzQvUnZUWjhNNlVLKzVVemhLOGpDZEx1TUdZTDZLdnpY
    R1JTZ2kzeUxnamV3UXRDUGtJVno2RDJRUXoKQ2tjaGVBbUNKOE1xeUp1NXpsenlaTWpBdm5uQVQ0
    NXRSQXhla3JzdTk0c1E0ZWdkUkNuYldTRHRZN2toK0JJbQpsSk5Yb0IxbEJNRUtJcTRRRFVPWG9S
    Z2ZmdURnaGplMVdyRzlNTCtIYmlzcS95Rk9Hd1hEOVJpWDhGNnN3Nlc0CmF2QXV2RHN6dWU1TDNz
    ejg1SytFQzRZL3dGVkROdlpvNFRZWGFvNlowZitsUUtjMHQ4RFFZemsxT1hWdThycDIKeUpNQzZh
    bExiQmZPREFMWnZZSDduN2RvMUFabHM0STlkMVA0am5rRHJRb3hCM1VxUTloVmwzTEVLUTczeEYx
    Twp5SzVHaEREWDhvVmZHS0Y1dStkZWNJc0g0WWFUdzdtUDNHRnhKU3F2MyswbFVGSm9pNUxjNWRh
    MTQ5cDkwSWRzCmhDRXhyb0wxKzdtcnlJa1hQZUZNNVRnTzlyMHJ2WmFCRk92VjJ6MGdwMzVaMCtM
    NFdQbGJ1RWpOL2x4UEZpbisKSGxVanI4Z1JzSTNxZkpPUUZ5LzlyS0lKUjBZLzhPbXd0LzhvVFdn
    eTFtZGVIbW1qazdqMW5Zc3ZDOUpTUTZadgpNbGRsVFRLQjN6aFRoVjErWFdZcDZyamQ1SlcxemJW
    V0VrTE54RTdHSlRoRVVHM3N6Z0JWR1A3cFNXVFVUc3FYCm5MUmJ3SE9vcTdoSHdnPT0KLS0tLS1F
    TkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRllEQ0NC
    RWlnQXdJQkFnSVFRQUYzSVRmVTZVSzQ3bmFxUEdRS3R6QU5CZ2txaGtpRzl3MEJBUXNGQURBLwpN
    U1F3SWdZRFZRUUtFeHRFYVdkcGRHRnNJRk5wWjI1aGRIVnlaU0JVY25WemRDQkRieTR4RnpBVkJn
    TlZCQU1UCkRrUlRWQ0JTYjI5MElFTkJJRmd6TUI0WERUSXhNREV5TURFNU1UUXdNMW9YRFRJME1E
    a3pNREU0TVRRd00xb3cKVHpFTE1Ba0dBMVVFQmhNQ1ZWTXhLVEFuQmdOVkJBb1RJRWx1ZEdWeWJt
    VjBJRk5sWTNWeWFYUjVJRkpsYzJWaApjbU5vSUVkeWIzVndNUlV3RXdZRFZRUURFd3hKVTFKSElG
    SnZiM1FnV0RFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElDRHdBd2dnSUtBb0lDQVFDdDZD
    Uno5QlEzODV1ZUsxY29ISWUrM0xmZk9KQ01ianptVjZCNDkzWEMKb3Y3MWFtNzJBRThvMjk1b2ht
    eEVrN2F4WS8wVUVtdS9IOUxxTVpzaGZ0RXpQTHBJOWQxNTM3TzQveEx4SVpwTAp3WXFHY1dsS1pt
    WnNqMzQ4Y0wrdEtTSUc4K1RBNW9DdTRrdVB0NWwrbEFPZjAwZVhmSmxJSTFQb09LNVBDbStECkx0
    RkpWNHlBZExiYUw5QTRqWHNEY0NFYmRmSXdQUHFQcnQzYVk2dnJGay9DamhGTGZzOEw2UCsxZHk3
    MHNudEsKNEV3U0pReHdqUU1wb09GVEpPd1QyZTRadnhDelNvdy9pYU5oVWQ2c2h3ZVU5R054N0M3
    aWIxdVlnZUdKWERSNQpiSGJ2TzVCaWVlYmJwSm92SnNYUUVPRU8zdGtRamhiN3QvZW85OGZsQWdl
    WWp6WUlsZWZpTjVZTk5uV2UrdzV5CnNSMmJ2QVA1U1FYWWdkMEZ0Q3JXUWVtc0FYYVZDZy9ZMzlX
    OUVoODFMeWdYYk5LWXdhZ0paSGR1UnplNnpxeFoKWG1pZGYzTFdpY1VHUVNrK1dUN2RKdlVreVJH
    bldxTk1RQjlHb1ptMXB6cFJib1k3bm4xeXB4SUZlRm50UGxGNApGUXNEajQzUUx3V3lQbnRLSEV0
    ekJSTDh4dXJnVUJOOFE1TjBzOHAwNTQ0ZkFRalFNTlJiY1RhMEI3ckJNREJjClNMZUNPNWltZldD
    S29xTXBnc3k2dllNRUc2S0RBMEdoMWdYeEc4SzI4S2g4aGp0R3FFZ3FpTngybW5hL0gycWwKUFJt
    UDZ6anpaTjdJS3cwS0tQLzMyK0lWUXRRaTBDZGQ0WG4rR09kd2lLMU81dG1MT3NiZEoxRnUvN3hr
    OVRORApUd0lEQVFBQm80SUJSakNDQVVJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBT0JnTlZIUThC
    QWY4RUJBTUNBUVl3ClN3WUlLd1lCQlFVSEFRRUVQekE5TURzR0NDc0dBUVVGQnpBQ2hpOW9kSFJ3
    T2k4dllYQndjeTVwWkdWdWRISjEKYzNRdVkyOXRMM0p2YjNSekwyUnpkSEp2YjNSallYZ3pMbkEz
    WXpBZkJnTlZIU01FR0RBV2dCVEVwN0drZXl4eAordHZoUzVCMS84UVZZSVdKRURCVUJnTlZIU0FF
    VFRCTE1BZ0dCbWVCREFFQ0FUQS9CZ3NyQmdFRUFZTGZFd0VCCkFUQXdNQzRHQ0NzR0FRVUZCd0lC
    RmlKb2RIUndPaTh2WTNCekxuSnZiM1F0ZURFdWJHVjBjMlZ1WTNKNWNIUXUKYjNKbk1Ed0dBMVVk
    SHdRMU1ETXdNYUF2b0MyR0syaDBkSEE2THk5amNtd3VhV1JsYm5SeWRYTjBMbU52YlM5RQpVMVJT
    VDA5VVEwRllNME5TVEM1amNtd3dIUVlEVlIwT0JCWUVGSG0wV2VaN3R1WGtBWE9BQ0lqSUdsajI2
    WnR1Ck1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUtjd0JzbG03L0RsTFFydDJNNTFvR3JTK280
    NCsveVFvREZWREMKNVd4Q3UyK2I5TFJQd2tTSUNIWE02d2ViRkdKdWVON3NKN281WFBXaW9XNVds
    SEFRVTdHNzVLL1Fvc01yQWRTVwo5TVVnTlRQNTJHRTI0SEdOdExpMXFvSkZsY0R5cVNNbzU5YWh5
    MmNJMnFCRExLb2JreC9KM3ZXcmFWMFQ5VnVHCldDTEtUVlhrY0dkdHdsZkZSamxCejRwWWcxaHRt
    ZjVYNkRZTzhBNGpxdjJJbDlEalhBNlVTYlcxRnpYU0xyOU8KaGU4WTRJV1M2d1k3YkNrakNXRGNS
    UUpNRWhnNzZmc08zdHhFK0ZpWXJ1cTlSVVdoaUYxbXl2NFE2VytDeUJGQwpEZnZwN09PR0FONmRF
    T000K3FSOXNkam9TWUtFQnBzcjZHdFBBUXc0ZHk3NTNlYzUKLS0tLS1FTkQgQ0VSVElGSUNBVEUt
    LS0tLQo=
  privkey.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdT
    TTQ5QXdFSEJHMHdhd0lCQVFRZzdqVmpiSFM5Q05pTncyZzcKdFhOUUF3dDA2NUhzR2NrNjRyRzBW
    WE52KzlpaFJBTkNBQVNCanh4UVd1SkZZdmUrN0NvYmw2aGJzNTk2QzFQdApmMUVZR2MzU1VZY2hK
    MmhHRkw1bGl1VzhseVd6Y2g4WnBqZzZnS1o1eGdpZTBMWjZrTU9VUE9jaQotLS0tLUVORCBQUklW
    QVRFIEtFWS0tLS0tCg==

