apiVersion: v1
kind: Service
metadata:
  name: aut-svc
spec:
  selector:
    app: aut
  ports:
    - name: aut
      port: 4000
      targetPort: 4000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aut
spec:
  selector:
    matchLabels:
      app: aut
  replicas: 2
  template:
    metadata:
      labels:
        app: aut
    spec:
      imagePullSecrets:
        - name: beren-registry
      containers:
        - name: aut
          image: docker.io/kebeney/beren:aut-0.0.68
          env:
            - name: VLT_PROTO
              value: https
            - name: VLT_IP
              value: '192.168.86.5'
            - name: VLT_TCP_PORT
              value: '8200'
            - name: LOG_PROTO
              value: https 
            - name: LOG_IP
              value: log-svc.default
            - name: LOG_HTTP_PORT
              value: '4600'
            - name: PGS_PROTO
              value: postgresql
            - name: PGS_IP
              value: pgs-svc.default
            - name: PGS_TCP_PORT
              value: '5432'
            - name: PGS_SSLMODE
              value: verify-ca
            - name: PGS_DATABASE
              value: postgres
            - name: TARGET_DB
              value: aut
          ports:
            - name: aut
              containerPort: 4000
          volumeMounts:
            - name: aut-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: false
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: false
      volumes:
        - name: aut-volume
          persistentVolumeClaim:
            claimName: aut-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
