apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: denkoech120@gmail.com
    privateKeySecretRef:
      name: account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.cert-manager.io
          solverName: dns01
          config:
            provider: your-dns-provider
            secretName: dns-credentials