apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
data:
  init-replica-set.sh: |
    #!/bin/bash

    # Wait for the MongoDB primary node to be ready
    until mongo --host mongodb-0.mongodb --eval "db.isMaster().ismaster" | grep true >/dev/null 2>&1; do
      echo "Waiting for MongoDB primary node to be ready..."
      sleep 5
    done

    # Initialize the replica set
    echo "Initializing MongoDB replica set..."
    mongo --host mongodb-0.mongodb --eval "rs.initiate()"

    # Add secondary nodes to the replica set
    echo "Adding MongoDB secondary nodes to the replica set..."
    mongo --host mongodb-0.mongodb --eval "rs.add('mongodb-1.mongodb')"
    mongo --host mongodb-0.mongodb --eval "rs.add('mongodb-2.mongodb')"
