apiVersion: v1
kind: Service
metadata:
  name: mgo
spec:
  selector:
    app: mgo
  ports:
    - name: mgo
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgo
spec:
  selector:
    matchLabels:
      app: mgo
  replicas: 2
  template:
    metadata:
      labels:
        app: mgo
    spec:
      containers:
        - name: mgo
          image: docker.io/library/mongo:6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: mgo-config-map
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mgo-secret
          ports:
            - name: mgo
              containerPort: 27017
          volumeMounts:
            - name: mgo-volume
              mountPath: /data/db
            - name: tls-certs
              mountPath: /opt/tls
              readOnly: false
      volumes:
        - name: mgo-config
          configMap:
            name: mgo-config-map
            defaultMode: 0640
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: tls-certs
          secret:
            secretName: beren-tls
            defaultMode: 0600
  volumeClaimTemplates:
    - metadata:
        name: mgo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 2Gi