apiVersion: v1
kind: Service
metadata:
  name: mgo-svc
spec:
  selector:
    app: mgo
  ports:
    - name: mgo
      port: 27017
      targetPort: 27017
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgo
spec:
  selector:
    matchLabels:
      app: mgo
  replicas: 2
  template:
    metadata:
      labels:
        app: mgo
    spec:
      hostNetwork: true
      containers:
        - name: mgo
          image: docker.io/library/mongo:6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mgo-secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mgo-secret
          args: ["--tlsMode=requireTLS", "--tlsCertificateKeyFile=/opt/tls/cert-with-key.pem"]
          ports:
            - name: mgo
              containerPort: 27017
          volumeMounts:
            - name: mgo-volume
              mountPath: /data/db
            - name: keb-certs
              mountPath: /opt/tls
      volumes:
        - name: tls-certs
          secret:
            secretName: mgo-tls
  volumeClaimTemplates:
    - metadata:
        name: mgo-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 2Gi