apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: acd-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: acd
  selector:
    matchLabels:
      app: acd-app
