apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: jen-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: jen
  selector:
    matchLabels:
      app: jen-app
