apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: log-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: log
  selector:
    matchLabels:
      app: log-app
