apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: mgo-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: mgo
  selector:
    matchLabels:
      app: mgo-app
