apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: oauth-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: oauth
  selector:
    matchLabels:
      app: oauth-app
