apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: pgs-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: pgs
  selector:
    matchLabels:
      app: pgs-app
