apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: vwt-app
  namespace: default
spec:
  endpoints:
  - interval: 30s
    port: vwt
  selector:
    matchLabels:
      app: vwt-app
