apiVersion: v1
kind: Service
metadata:
  name: rnt-svc
  labels:
    app: rnt-app
spec:
  selector:
    app: rnt
  ports:
    - name: rnt
      port: 4200
      targetPort: 4200
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnt
spec:
  selector:
    matchLabels:
      app: rnt
  replicas: 2
  template:
    metadata:
      labels:
        app: rnt
    spec:
      imagePullSecrets:
        - name: beren-registry
      containers:
        - name: rnt
          image: docker.io/kebeney/beren:rnt-0.0.82
          envFrom:
            - configMapRef:
                name: rnt-configmap
          ports:
            - name: rnt
              containerPort: 4200
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: rnt-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: true
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: true
      volumes:
        - name: rnt-volume
          persistentVolumeClaim:
            claimName: rnt-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
