apiVersion: v1
kind: Service
metadata:
  name: rnt-svc
spec:
  selector:
    app: rnt
  ports:
    - name: rnt
      port: 4200
      targetPort: 4200
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnt
spec:
  selector:
    matchLabels:
      app: rnt
  replicas: 2
  template:
    metadata:
      labels:
        app: rnt
    spec:
      imagePullSecrets:
        - name: beren-registry
      containers:
        - name: rnt
          image: docker.io/kebeney/beren:rnt-0.0.75
          env:
            - name: VLT_PROTO
              value: https
            - name: VLT_IP
              value: '192.168.86.5'
            - name: VLT_TCP_PORT
              value: '8200'
            - name: LOG_PROTO
              value: https 
            - name: LOG_IP
              value: log-svc.default
            - name: LOG_HTTP_PORT
              value: '4600'
            - name: MGO_PROTO
              value: mongodb
            - name: MGO_IP
              value: mgo-svc.default
            - name: MGO_HTTP_PORT
              value: '27017'
            - name: MGO_TLSMODE
              value: 'true'
            - name: TARGET_DB
              value: rnt
            - name: ROLE_ID
              value: 9a4d7850-7efb-8320-14a9-4123391a6d94
            - name: SECRET_ID
              value: d3ca3b11-545d-8b60-0f82-a2eb451eec5e
          ports:
            - name: rnt
              containerPort: 4200
          volumeMounts:
            - name: rnt-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: true
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: true
      volumes:
        - name: rnt-volume
          persistentVolumeClaim:
            claimName: rnt-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
