apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jen-pvc
spec:
  storageClassName: local-storage
  volumeName: jen-pv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi