apiVersion: v1
kind: Secret
metadata:
  name: beren-registry
type: kubernetes.io/dockercfg
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2RvY2tlci5pby9rZWJlbmV5IjogewogICAgICAidXNlcm5hbWUiOiAia2ViZW5leSIsCiAgICAgICJwYXNzd29yZCI6ICI4MDc2ZDlkYi1kYzI1LTRjNDItOWZkNy1jOWE5ZTFhOTRkODgiLAogICAgICAiZW1haWwiOiAiYmtlYmVuZXlAeWFob28uY29tIiwKICAgICAgImF1dGgiOiAiYTJWaVpXNWxlVG80TURjMlpEbGtZaTFrWXpJMUxUUmpOREl0T1daa055MWpPV0U1WlRGaE9UUmtPRGc9IgogICAgfQogIH0KfQo=
