apiVersion: v1
kind: Service
metadata:
  name: mps
spec:
  selector:
    app: mps
  ports:
    - name: mps
      port: 4300
      targetPort: 4300
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mps
spec:
  selector:
    matchLabels:
      app: mps
  replicas: 2
  template:
    metadata:
      labels:
        app: mps
    spec:
      containers:
        - name: mps
          image: docker.io/kebeney/beren:mps-0.0.38
          env:
            - name: VLT_PROTO
              value: https
            - name: VLT_IP
              value: kberen.com
            - name: VLT_TCP_PORT
              value: 8200
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: mps-volume
              mountPath: /opt/pgs/data
            - name: tls-certs
              mountPath: /opt/pgs/tls
              readOnly: false
      volumes:
        - name: mps-volume
          persistentVolumeClaim:
            claimName: mps-pvc
        - name: tls-certs
          secret:
            secretName: beren-tls
            defaultMode: 0600
