apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mps-hpa
spec:
  behavior:
  scaleDown:
    stabilizationWindowSeconds: 300
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mps
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target: 
        type: AverageValue
        averageValue: 100Mi
