apiVersion: v1
kind: ConfigMap
metadata:
  name: acd-configmap
data:
  NODE_ENV: development
  JWKS_CACHE_TIME: 24H
  VLT_PROTO: https
  VLT_IP: '192.168.86.204'
  VLT_TCP_PORT: '8200'
  LOG_PROTO: http
  LOG_IP: log-svc.default.svc.cluster.local
  LOG_HTTP_PORT: '4600'
  OAUTH_PROTO: http
  OAUTH_IP: oauth-svc.default.svc.cluster.local
  OAUTH_HTTP_PORT: '4700'
  PGS_PROTO: postgresql
  PGS_IP: psg-svc.default.svc.cluster.local
  PGS_TCP_PORT: '5432'
  PGS_SSLMODE: allow
  COOKIE_MAX_AGE_HRS: '24'
  TARGET_DB: acd
  ROLE_ID: 263246b9-1ec5-29ac-9055-495a81dc811b
  SECRET_ID: 91d61a22-c469-28bc-6316-07485400b51a
  ACD_PROTO: http
  ACD_IP: acd-svc.default.svc.cluster.local
  ACD_HTTP_PORT: '3000'
