apiVersion: v1
kind: Service
metadata:
  name: acd-svc
spec:
  selector:
    app: acd
  ports:
    - name: acd
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acd
spec:
  selector:
    matchLabels:
      app: acd
  replicas: 2
  template:
    metadata:
      labels:
        app: acd
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: beren-registry
      containers:
        - name: acd
          image: docker.io/kebeney/beren:acd-0.0.11
          env:
            - name: NODE_ENV
              value: development
            - name: JWKS_CACHE_TIME
              value: 24H
            - name: VLT_PROTO
              value: https
            - name: VLT_IP
              value: '192.168.86.4'
            - name: VLT_TCP_PORT
              value: '8200'
            - name: LOG_PROTO
              value: https 
            - name: LOG_IP
              value: log-svc.default
            - name: LOG_HTTP_PORT
              value: '4600'
            - name: AUT_PROTO
              value: https
            - name: AUT_IP
              value: aut-svc.default
            - name: AUT_HTTP_PORT
              value: '4000'
            - name: TARGET_DB
              value: acd
            - name: ROLE_ID
              value: b638459b-8a20-0fe7-7751-34bbca7b850a
            - name: SECRET_ID
              value: d49fbed4-865a-cd90-aec8-c999a3d2d41d
            - name: ACD_PROTO
              value: http
            - name: ACD_IP
              value: 'aut-svc.default'
            - name: ACD_HTTP_PORT
              value: '3000'
          ports:
            - name: academy
              containerPort: 3000
          volumeMounts:
            - name: acd-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: false
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: false
      volumes:
        - name: acd-volume
          persistentVolumeClaim:
            claimName: acd-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
