apiVersion: v1
kind: Service
metadata:
  name: acd-svc
  labels:
    app: acd-app
spec:
  selector:
    app: acd
  ports:
    - name: acd
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acd
spec:
  selector:
    matchLabels:
      app: acd
  replicas: 2
  template:
    metadata:
      labels:
        app: acd
    spec:
      imagePullSecrets:
        - name: beren
      containers:
        - name: acd
          image: docker.io/kebeney/beren:acd-0.0.12
          envFrom:
            - configMapRef:
                name: acd-configmap
          ports:
            - name: academy
              containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: acd-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: false
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: false
      volumes:
        - name: acd-volume
          persistentVolumeClaim:
            claimName: acd-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
