apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pgs-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pgs-secret
            - name: POSTGRES_ALLOW_CONNECTIONS
              value: "true"
          args: ["-c", "ssl=on", "-c", "ssl_cert_file=/opt/tls/..data/tls.crt", "-c", "ssl_key_file=/opt/tls/..data/tls.key", "-c", "ssl_ca_file=/opt/tls/..data/ca.crt"]
          ports:
            - name: postgres
              containerPort: 5432
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: pgs-volume
              mountPath: /var/lib/postgresql/data
            - name: tls-certs
              mountPath: /opt/tls
            - name: pgs-conf
              mountPath: /var/lib/postgresql/data/postgresql.conf
            - name: pgs-hba
              mountPath: /var/lib/postgresql/data/pg_hba.conf
      securityContext:
        fsGroup: 70
      volumes:
        - name: tls-certs
          secret:
            secretName: selfsigned-cert-tls
            defaultMode: 0640
        - name: pgs-conf
          configMap:
            name: pgs-conf
            defaultMode: 0644
            items:
              - key: postgresql.conf
                path: postgresql.conf
        - name: pgs-hba
          configMap:
            name: pgs-hba
            defaultMode: 0644
            items:
              - key: pg_hba.conf
                path: pg_hba.conf
          
  volumeClaimTemplates:
    - metadata:
        name: pgs-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 2Gi