apiVersion: v1
kind: Service
metadata:
  name: pgs
spec:
  selector:
    app: pgs
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgs
spec:
  selector:
    matchLabels:
      app: pgs
  replicas: 1
  template:
    metadata:
      labels:
        app: pgs
    spec:
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "cp /opt/tls/cert.pem /opt/tls/priv-key.pem /tmp/ && chmod 0600 /tmp/priv-key.pem && chmod 0640 /tmp/cert.pem"]
          volumeMounts:
            - name: tls-certs
              mountPath: /opt/tls
            - name: temp
              mountPath: /tmp
      containers:
        - name: pgs
          image: docker.io/library/postgres:15-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pgs-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pgs-secret
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: pgs-volume
              mountPath: /var/lib/postgresql/data
            # - name: pgs-config
            #   mountPath: pg_hba.conf
            #   readOnly: false
            - name: tls-certs
              mountPath: /opt/tls
              readOnly: true
          args:
            - "-c"
            - "ssl=on"
            - "-c"
            - "ssl_cert_file=/opt/tls/cert.pem"
            - "-c"
            - "ssl_key_file=/opt/tls/priv-key.pem"
      volumes:
        # - name: pgs-config
        #   configMap:
        #     name: pgs-config-map
        #     items:
        #       - key: postgresql.conf
        #         path: postgresql.conf
        #       - key: pg_hba.conf
        #         path: pg_hba.conf
        - name: tls-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: temp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: pgs-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: managed-nfs-storage
        resources:
          requests:
            storage: 2Gi