apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  storageClassName: local-storage
  volumeName: vault-pv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi