apiVersion: v1
kind: Service
metadata:
  name: oauth-svc
spec:
  selector:
    app: oauth
  ports:
    - name: oauth
      port: 4700
      targetPort: 4700
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth
    spec:
      imagePullSecrets:
        - name: beren-registry
      containers:
        - name: oauth
          image: docker.io/kebeney/beren:oauth-0.0.11
          envFrom:
            - configMapRef:
                name: oauth-configmap
          ports:
            - name: oauth
              containerPort: 4700
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - name: oauth-volume
              mountPath: /opt/shared/data
            - name: keb-certs
              mountPath: /opt/shared/tls/keb
              readOnly: false
            - name: le-certs
              mountPath: /opt/shared/tls/le
              readOnly: false
      volumes:
        - name: oauth-volume
          persistentVolumeClaim:
            claimName: oauth-pvc
        - name: le-certs
          secret:
            secretName: le-tls
            defaultMode: 0600
        - name: keb-certs
          secret:
            secretName: keb-tls
            defaultMode: 0600
