apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-pvc
spec:
  storageClassName: local-storage
  volumeName: oauth-pv
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi